name: notes_app
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  uuid: ^3.0.1
  intl: ^0.17.0
  dartz: ^0.10.0-nullsafety.1
  mockito: ^5.0.0
  sqflite: ^2.0.0+2
  path: ^1.8.0
  flutter_bloc: ^7.0.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
