name: todo_application_ddd
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.7.1
  flutter_bloc: ^3.2.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1

dev_dependencies:
  flutter_test:
  

    sdk: flutter

  build_runner:
  freezed: ^0.10.5





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
