name: todo_application_ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.1
  cloud_firestore: ^0.13.6
  dartz: ^0.9.1
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  flushbar: ^1.10.4
  flutter_bloc: ^4.0.0
  freezed_annotation: ^0.7.1
  get_it: ^4.0.2
  google_sign_in: ^4.5.1
  injectable: ^0.4.0+1
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  rxdart: ^0.24.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:

    sdk: flutter
  auto_route_generator: ^0.6.0
  build_runner: null
  freezed: ^0.10.9
  injectable_generator: ^0.4.0
  json_serializable: ^3.3.0
  lint: ^1.2.0

flutter:

  uses-material-design: true
